@startuml clases
    class Cliente{
        -id: Long
        -nombre: String
        -apellido: String
        -dni: String
        -ruc: String
        -razonSocial: String
        -correo: String
        -direccion: String
        -telefono: String
        -tipoCliente: TipoCliente
        -vehiculo: List<Vehiculo>
        -tipoPago: TipoPago
    }

    enum TipoPago{
        EFECTIVO
        TARJETA
    }

    enum TipoCliente{
        PERSONA_NATURAL
        EMPRESA
        CLIENTE_NORMAL
    }

    class Direccion{
        -id: Long
        -cooperativa: String
        -calle: String
        -distrito: String
        -departamento: String
    }

    class Vehiculo{
        -id: Long
        -marca: String
        -modelo: String
        -color: String
        -anio: String
        -placa: String
        -cliente: Cliente
    }

    class Servicios{
        -id: Long
        -nombre: String
        -costo: Double
        -descripcion: String
        -tiempoEstimado: Double
    }

    class Tecnico{
        -id: Long
        -nombre: String 
        -apellido: String 
        -dni: String
        -fechaNacimiento: Date 
        -sueldo: Double 
        -telefono: String 
        -direccion: Direccion
    }

    class OrdenTrabajo{
        -id: Long
        -vehiculo: Vehiculo
        -fechaIngreso: Date
        -fechaSalida: Date
        -servicios: List<Servicios>
        -costoTotal: Double
        -comentario: String
        -estado: Estado
    }

    enum Estado{
        PENDIENTE
        EN_PROCESO
        FINALIZADO
    }

    class Factura{
        -id: Long
        -vehiculo: Vehiculo
        -cliente: Cliente
        -ordenTrabajo: OrdenTrabajo
        -fecha: Date
    }

    Cliente --* Vehiculo
    Cliente -- Direccion
    Tecnico -- Direccion
    Vehiculo -- Cliente
    Tecnico --* OrdenTrabajo
    OrdenTrabajo --* Tecnico
    OrdenTrabajo --* Factura
    Factura --* OrdenTrabajo
    Servicios --* OrdenTrabajo
    OrdenTrabajo --* Servicios

@enduml 