@startuml GestionClientes
'left to right direction
actor "Administrador" as Admin

rectangle "Gestión de Clientes" {
    usecase (Gestionar Clientes) as UC1
    usecase (Registrar Cliente) as UC2
    usecase (Actualizar Cliente) as UC3
    usecase (Buscar Cliente) as UC4
    usecase (Eliminar Cliente) as UC5
    usecase (Validar Datos) as UC6
}

Admin --> UC1
UC1 ..> UC2 : include
UC1 ..> UC3 : include
UC1 ..> UC4 : include
UC1 ..> UC5 : include
UC2 ..> UC6 : include
UC3 ..> UC6 : include
UC4 ..> UC3 : extend
@enduml